const STARTER_WORDS=[
{swedish:'ställa in',english:'cancel',example:'Mötet måste ställas in på grund av ovädret.'},
{swedish:'ta reda på',english:'find out',example:'Jag ska ta reda på när bussen går.'},
{swedish:'hålla med',english:'agree',example:'Jag håller med om att svenska är svårt ibland.'},
{swedish:'på grund av',english:'because of',example:'Tåget är sent på grund av ett tekniskt fel.'},
{swedish:'det visar sig att',english:'it turns out that',example:'Det visar sig att vägen redan är öppen.'}];
const STORIES=[
'Ett möte i Göteborg skulle börja klockan nio, men arrangörerna behövde ställa in det på grund av ett tekniskt problem. Andrew försökte ta reda på vad som hade hänt. Det visar sig att lokalen saknade el. Lisa höll med om att det var bättre att boka en ny dag.',
'Kommunen ville ställa in arbetet på en gata i Majorna på grund av kraftigt regn. En reporter försökte ta reda på när arbetet skulle fortsätta. Det visar sig att arbetet börjar igen på måndag. Många boende håller med om beslutet.',
'Andrew läste en nyhet om ett tåg som hade ställts in på grund av ett signalfel. Han ville ta reda på om ersättningsbussar fanns. Det visar sig att bussarna redan väntade utanför stationen, och de flesta resenärer höll med om att informationen var tydlig.'
];
let words=JSON.parse(localStorage.getItem('svenska-nara-words')||'null')||STARTER_WORDS;let storyIndex=0;
const esc=s=>String(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function renderStarter(){document.querySelector('#starterWords').innerHTML=STARTER_WORDS.map((w,i)=>`<button class="word-card" data-word="${i}"><strong>${w.swedish}</strong><span>${w.english}</span></button>`).join('');document.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{const w=STARTER_WORDS[+b.dataset.word];alert(`${w.swedish} = ${w.english}\n\n${w.example}`)})}
function renderWords(){localStorage.setItem('svenska-nara-words',JSON.stringify(words));document.querySelector('#savedWords').innerHTML=words.map(w=>`<div><strong>${esc(w.swedish)}</strong><span>${esc(w.english)}</span></div>`).join('')}
function renderStory(){document.querySelector('#story').textContent=STORIES[storyIndex]}
function newsCards(items){return items.slice(0,5).map(item=>`<article class="news-card" data-news='${encodeURIComponent(JSON.stringify(item))}'><small>${esc(item.source)}</small><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p><span>Läs och lär →</span></article>`).join('')||'<p class="muted">Inga nyheter kunde hämtas just nu.</p>'}
function bindNews(){document.querySelectorAll('[data-news]').forEach(card=>card.onclick=()=>openNews(JSON.parse(decodeURIComponent(card.dataset.news))))}
function openNews(item){document.querySelector('#modal').innerHTML=`<div class="modal-backdrop"><div class="modal"><button class="close">×</button><p class="eyebrow">${esc(item.source)}</p><h2>${esc(item.title)}</h2><p id="selectable">${esc(item.description||'Öppna originalartikeln för att läsa mer.')}</p><p class="tip">Markera ett svårt ord eller uttryck i texten ovan. Det sparas i Mina ord.</p><a href="${esc(item.link)}" target="_blank" rel="noreferrer">Öppna den fria originalartikeln ↗</a></div></div>`;document.querySelector('.close').onclick=closeModal;document.querySelector('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()};document.querySelector('#selectable').onmouseup=()=>{const text=getSelection().toString().trim().toLowerCase();if(text&&!words.some(w=>w.swedish===text)){words.unshift({swedish:text,english:'lägg till betydelse',example:item.title});renderWords();alert(`Sparat: ${text}`)}}}
function closeModal(){document.querySelector('#modal').innerHTML=''}
async function loadNews(){try{const data=await fetch('/api/news').then(r=>r.json());document.querySelector('#localNews').innerHTML=newsCards(data.news.filter(n=>n.region==='Göteborg & Väst'));document.querySelector('#nationalNews').innerHTML=newsCards(data.news.filter(n=>n.region==='Sverige'));bindNews()}catch(e){document.querySelector('#localNews').innerHTML='<p class="muted">Nyhetsflödet kunde inte laddas.</p>';document.querySelector('#nationalNews').innerHTML='<p class="muted">Nyhetsflödet kunde inte laddas.</p>'}}
renderStarter();renderWords();renderStory();loadNews();document.querySelector('#newStory').onclick=()=>{storyIndex=(storyIndex+1)%STORIES.length;renderStory()};document.querySelector('#checkAnswer').onclick=()=>{const ok=document.querySelector('#answer').value.trim().toLowerCase()==='cancel';document.querySelector('#result').textContent=ok?'Correct ✓':'Not quite. “Ställa in” means “cancel”.'};