const STARTER=[
 {swedish:'ställa in',english:'cancel',examples:['De måste ställa in mötet i morgon.','Matchen ställdes in på grund av regnet.','Vi vill inte ställa in resan.','Varför blev konserten inställd?']},
 {swedish:'ta reda på',english:'find out',examples:['Jag ska ta reda på när bussen går.','Kan du ta reda på vad som hände?','Hon försöker ta reda på vem som ringde.','Vi behöver ta reda på mer information.']},
 {swedish:'hålla med',english:'agree',examples:['Jag håller med dig.','Lisa höll med om att det var en bra idé.','Alla håller inte med om beslutet.','Håller du med mig?']},
 {swedish:'på grund av',english:'because of',examples:['Tåget är sent på grund av ett tekniskt fel.','Vägen är stängd på grund av olyckan.','Vi stannade hemma på grund av vädret.','Mötet flyttades på grund av sjukdom.']},
 {swedish:'det visar sig att',english:'it turns out that',examples:['Det visar sig att vägen redan är öppen.','Det visade sig att nyheten var fel.','Det visar sig att hon känner min granne.','Efter kontrollen visar det sig att allt fungerar.']}
];
const SECTIONS=[['Kungälv & Marstrand','Mycket nära dig'],['Göteborg','Göteborg'],['Stenungsund & Tjörn','Nordvästkusten'],['Västsverige','Västsverige'],['Sverige','Sverige idag']];
let words=JSON.parse(localStorage.getItem('svenska-nara-clean')||'null')||STARTER.map(w=>({...w,status:'learning'}));
let currentArticle=null,currentUtterance=null;
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text){const el=q('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function learning(){return words.filter(w=>w.status!=='mastered')}function mastered(){return words.filter(w=>w.status==='mastered')}
function save(){localStorage.setItem('svenska-nara-clean',JSON.stringify(words));renderPractice()}
function exampleSet(word,context=''){const known=STARTER.find(x=>x.swedish===word)?.examples;if(known)return known;return [...new Set([context,`Jag såg ordet ${word} i en nyhet.`,`Vad betyder ${word}?`,`Jag vill komma ihåg ordet ${word}.`].filter(Boolean))].slice(0,4)}
async function translate(text){const r=await fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const d=await r.json();if(!r.ok||!d.translation)throw new Error();return d.translation}
async function addWord(raw,context=''){const word=String(raw||'').trim().toLowerCase().replace(/^[^a-zåäöéü-]+|[^a-zåäöéü-]+$/gi,'');if(!word)return;let existing=words.find(w=>w.swedish===word);if(existing){existing.status='learning';if(context&&!existing.examples?.includes(context))existing.examples=[context,...(existing.examples||[])].slice(0,4);save();toast(`Redan sparat: ${word}`);return}const item={swedish:word,english:'Översätter…',examples:exampleSet(word,context),status:'learning'};words.unshift(item);save();toast(`Sparat: ${word}`);try{item.english=await translate(word)}catch{item.english='English meaning unavailable'}save()}
function renderStarter(){q('#starterWords').innerHTML=STARTER.map((w,i)=>`<button class="starter-card" data-start="${i}"><strong>${esc(w.swedish)}</strong><span>${esc(w.english)}</span></button>`).join('');qa('[data-start]').forEach(b=>b.onclick=()=>addWord(STARTER[+b.dataset.start].swedish,STARTER[+b.dataset.start].examples[0]))}
function sentenceContaining(text,word){return((String(text||'').match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[]).find(s=>s.toLowerCase().includes(word.toLowerCase()))||'').trim()}
function practiceCard(w,index,isDone){const list=isDone?'mastered':'learning';const examples=(w.examples?.length?w.examples:exampleSet(w.swedish)).slice(0,4);return`<article class="practice-card"><div class="practice-head"><div class="practice-title"><strong>${esc(w.swedish)}</strong><span>${esc(w.english||'')}</span></div><div class="practice-actions"><button class="action" data-word-audio="${list}:${index}">🔊 Lyssna på ordet</button>${isDone?`<button class="action" data-reactivate="${index}">Träna igen</button>`:`<button class="action understood" data-understood="${index}">✓ Word understood</button>`}</div></div><div class="examples"><p class="examples-label">ENKLA MENINGAR</p>${examples.map((s,i)=>`<div class="example-row"><p>${esc(s)}</p><button class="listen-button" data-sentence="${list}:${index}:${i}">▶ Lyssna</button></div>`).join('')}</div></article>`}
function renderPractice(){const a=learning(),m=mastered();q('#learningCount').textContent=a.length;q('#practiceWords').innerHTML=a.length?a.map((w,i)=>practiceCard(w,i,false)).join(''):'<section class="panel"><p>Inga aktiva ord.</p></section>';q('#masteredWords').innerHTML=m.length?m.map((w,i)=>practiceCard(w,i,true)).join(''):'<section class="panel"><p>Inga förstådda ord ännu.</p></section>';qa('[data-understood]').forEach(b=>b.onclick=()=>{a[+b.dataset.understood].status='mastered';save();toast('Flyttat till Förstådda ord')});qa('[data-reactivate]').forEach(b=>b.onclick=()=>{m[+b.dataset.reactivate].status='learning';save();toast('Ordet är tillbaka i träning')});qa('[data-word-audio]').forEach(b=>b.onclick=()=>{const [type,i]=b.dataset.wordAudio.split(':');const item=(type==='mastered'?m:a)[+i];speak(item.swedish,b)});qa('[data-sentence]').forEach(b=>b.onclick=()=>{const [type,i,j]=b.dataset.sentence.split(':');const item=(type==='mastered'?m:a)[+i];speak(item.examples[+j],b)})}
function getVoice(){const voices=speechSynthesis.getVoices();return voices.find(v=>/^sv(-|_)/i.test(v.lang)&&v.localService)||voices.find(v=>/^sv(-|_)/i.test(v.lang))||voices.find(v=>v.localService)||voices[0]||null}
function stopSpeech(){if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.resume()}currentUtterance=null;qa('.listen-button,.action,.tool').forEach(b=>b.classList.remove('playing'))}
function speak(text,button){if(!('speechSynthesis'in window)){toast('Din webbläsare stöder inte uppläsning');return}stopSpeech();const utterance=new SpeechSynthesisUtterance(String(text));currentUtterance=utterance;utterance.lang='sv-SE';utterance.rate=.88;utterance.pitch=1;utterance.volume=1;const voice=getVoice();if(voice)utterance.voice=voice;if(button)button.classList.add('playing');utterance.onstart=()=>toast(voice?`Spelar med ${voice.name}`:'Spelar med enhetens röst');utterance.onend=()=>{if(button)button.classList.remove('playing');currentUtterance=null};utterance.onerror=e=>{if(button)button.classList.remove('playing');currentUtterance=null;toast(`Ljudet kunde inte starta (${e.error||'okänt fel'})`)};speechSynthesis.resume();setTimeout(()=>speechSynthesis.speak(utterance),80)}
function tokenise(text){return String(text||'').split(/(\s+)/).map(part=>{if(/^\s+$/.test(part))return part;const clean=part.replace(/^[^a-zåäöéü-]+|[^a-zåäöéü-]+$/gi,'');return clean?`<button class="click-word" data-click-word="${encodeURIComponent(clean.toLowerCase())}">${esc(part)}</button>`:esc(part)}).join('')}
function newsCards(items){return items.slice(0,8).map(item=>`<article class="news-card"><small>${esc(item.source)} · ${new Date(item.published).toLocaleDateString('sv-SE')}</small><h3>${esc(item.title)}</h3><p>${esc(item.description||'')}</p><button data-news="${encodeURIComponent(JSON.stringify(item))}">Läs inne på Svenska Nära →</button></article>`).join('')||'<p class="muted">Inga aktuella nyheter kunde hämtas.</p>'}
async function loadNews(){try{const r=await fetch('/api/news',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error();q('#newsSections').innerHTML=SECTIONS.map(([region,label])=>`<section class="news-section"><div class="section-heading"><div><p class="eyebrow">${esc(label.toUpperCase())}</p><h2>${esc(region)}</h2></div><span>Uppdateras automatiskt</span></div><div class="news-list">${newsCards(d.news.filter(n=>n.region===region))}</div></section>`).join('');qa('[data-news]').forEach(b=>b.onclick=()=>openArticle(JSON.parse(decodeURIComponent(b.dataset.news))))}catch{q('#newsSections').innerHTML='<section class="panel"><p>Nyheterna kunde inte laddas just nu.</p></section>'}}
async function openArticle(item){currentArticle=item;document.body.classList.add('reader-open');q('#reader').innerHTML=`<section class="reader"><div class="reader-bar"><button id="closeReader">← Till nyheterna</button><span>${esc(item.source)}</span></div><div class="reader-layout"><article><p class="eyebrow">${esc(item.source)}</p><h1>${esc(item.title)}</h1><div class="reader-tools"><button id="listenArticle" class="tool primary">▶ Lyssna</button><button id="stopArticle" class="tool">■ Stoppa</button><button id="translateArticle" class="tool">Translate to English</button></div><div id="articleStatus" class="article-status">Hämtar artikeln…</div><div id="articleText" class="article-text"></div><div id="articleTranslation" class="translation hidden"></div></article><aside class="reader-side"><h3>Spara svåra ord</h3><p>Klicka på ett ord. Markera flera ord och använd knappen nedan.</p><button id="savePhrase" class="tool">+ Spara markerad fras</button></aside></div></section>`;q('#closeReader').onclick=closeReader;q('#stopArticle').onclick=stopSpeech;q('#listenArticle').onclick=e=>speak(`${item.title}. ${q('#articleText').innerText}`,e.currentTarget);q('#savePhrase').onclick=()=>{const s=getSelection().toString().trim();s?addWord(s,item.title):toast('Markera en fras först')};q('#translateArticle').onclick=translateArticle;try{const r=await fetch(`/api/article?url=${encodeURIComponent(item.link)}`),d=await r.json();if(!r.ok||!d.body)throw new Error();q('#articleStatus').textContent='Artikeln är laddad. Klicka på ett svårt ord för att spara det.';q('#articleText').innerHTML=d.body.split(/\n+/).filter(Boolean).map(p=>`<p>${tokenise(p)}</p>`).join('')}catch{q('#articleStatus').textContent='Hela artikeln kunde inte hämtas. Sammanfattningen visas.';q('#articleText').innerHTML=`<p>${tokenise(item.description)}</p>`}q('#articleText').onclick=e=>{const b=e.target.closest('[data-click-word]');if(!b)return;const word=decodeURIComponent(b.dataset.clickWord);addWord(word,sentenceContaining(q('#articleText').innerText,word)||item.title)}}
function closeReader(){stopSpeech();document.body.classList.remove('reader-open');q('#reader').innerHTML=''}
async function translateArticle(){const box=q('#articleTranslation'),button=q('#translateArticle');if(!box.classList.contains('hidden')){box.classList.add('hidden');button.textContent='Translate to English';return}button.disabled=true;button.textContent='Translating…';try{box.textContent=await translate(`${currentArticle.title}\n\n${q('#articleText').innerText}`);box.classList.remove('hidden');button.textContent='Hide English translation'}catch{toast('Översättningen kunde inte skapas');button.textContent='Try translation again'}button.disabled=false}
qa('[data-view]').forEach(b=>b.onclick=()=>{qa('.tab-button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');q(`#${b.dataset.view}`).classList.add('active')});
renderStarter();renderPractice();loadNews();if('speechSynthesis'in window){speechSynthesis.getVoices();speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices()}
